"""Updated datatypes to improve storage efficiency and increase maximum int size

Revision ID: 0c0ceb2a2123
Revises: 5390c0dead7f
Create Date: 2021-05-27 13:09:06.024061

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0c0ceb2a2123'
down_revision = '5390c0dead7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'active',
               existing_type=mysql.SMALLINT(display_width=6),
               type_=mysql.TINYINT(unsigned=True),
               existing_nullable=False)
    op.alter_column('users', 'account_type',
               existing_type=mysql.SMALLINT(display_width=6),
               type_=mysql.TINYINT(unsigned=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'account_type',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=mysql.SMALLINT(display_width=6),
               existing_nullable=False)
    op.alter_column('users', 'active',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=mysql.SMALLINT(display_width=6),
               existing_nullable=False)
    # ### end Alembic commands ###
