"""empty message

Revision ID: 5390c0dead7f
Revises: 
Create Date: 2021-05-26 23:46:23.206016

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5390c0dead7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('map_files', 'file_location',
               existing_type=mysql.TEXT(),
               type_=sqlalchemy_utils.types.uuid.UUIDType(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('map_files', 'file_location',
               existing_type=sqlalchemy_utils.types.uuid.UUIDType(),
               type_=mysql.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
